### ISSUE TITLE
Syntax error with string interpolation

### ISSUE THREAD

**Issue by ptittof57** [Visual-Stylecop/Visual-StyleCop#14]
Comment from Visual Studio Gallery:

 Hi,

First, thanks for this great Tool we are using on a daily basis.
Then talking about C#6, I have found a string interpolation syntax that seems not to be recognized by the parser (v 4.7.54) while correctly compiled and run in VS2015 :

WriteLine($"{argumentName}[{argIndex}] = \"{arguments[argIndex]}\"");

where argumentName is a const string (local auto)
where argIndex is an int
where arguments is an array of string

  Thanks for fixing.

**Comment by ptittof57** [comment]
Fix for next release.

**Comment by ptittof57** [comment]
Error found with regex

**Comment by softwaretecture** [comment]
Hi, the latest build of StyleCop from codplex is 4.7.54 which does not have this fix for string interpolation.  https://stylecop.codeplex.com/releases/view/621306. 
Is the approach now to grab the latest code and compile it or there is already a compiled latest version posted somewhere? Thanks
