### ISSUE TITLE
Syntax error in C# 6 while compiling OK

### ISSUE THREAD

**Issue by FredyFLU** [Visual-Stylecop/Visual-StyleCop#18]
return modules?[0] is incorrectly reported as syntax error in the following code snippet (v4.7.55.26)

private static Module AssemblyModule
        {
            get
            {
                Module[] modules = Assembly.GetExecutingAssembly().GetModules();
                Contract.Assume(modules?.Length > 0);
                return modules?[0];
            }
        }

Thanks for the product !

**Comment by ptittof57** [comment]
Fixed in the next release.
