### ISSUE TITLE
SA0102 - syntax error - wrapped string

### ISSUE THREAD

**Issue by WiktorJagusiak** [Visual-Stylecop/Visual-StyleCop#20]
Strings containing new lines and created by verbatim string literal causes SA0102.  
Example:
    const string Query = @"delete from [dbo].[OrganizationEventEntry] where [idOrganization] = 104
                                       insert into [dbo].[OrganizationEventEntry](idOrganization, idTimezone (...)

**Comment by ptittof57** [comment]
@WiktorJagusiak could you give me more information like your version and file encoding you use (File\Advanced Save Options).

You can send me the complete file by mail: VisualStyleCop@gmail.com

Because I can't reproduce this issue with your example.

**Comment by WiktorJagusiak** [comment]
Sure. I sent you an email.

**Comment by vanko-dev** [comment]
I have similar problem. SA0102 occurs in all cases when used verbatim string literals.
Version of StyleCop.CSharp.dll - 4.7.56.0
I run it under msbuild.
Files encoding: UTF8.

**Comment by ptittof57** [comment]
Fixed in version 4.7.57.0. Let me know if you have any other issues.

**Comment by WiktorJagusiak** [comment]
Thank you. It was very fast response :-)
22 wrz 2015 16:17 "Christophe HEISER" <notifications@github.com> napisał(a):

**Comment by WiktorJagusiak** [comment]
Indeed, problem with verbatim strings is solved. But problems with strings
as key of index like

Distributions = new List<string> { reader["Distribution1"].ToString(),
reader["Distribution2"].ToString() },
Still exists.

Problems from example 2 and 3 also.

// -- Example 2 (new long?[0])
        public long?[] GetSelectedOrgIds()
        {
            return BulkScheduleEvents == null
                ? new long?[0]
                : BulkScheduleEvents.Where(a => a.IsChecked).Select(a
=> a.OrganizationId).ToArray();
        }

// Example 3 (AlternateNames)
 var expected = new InstitutionalInfo
                {
                    AgendaSource = _institutionalInfo.AgendaSource != 0,
                    AudioSource = _institutionalInfo.AudioSource != 0,
                    Calendar = _institutionalInfo.Calendar,
                    IdConferenceFrequency =
_institutionalInfo.IdConferenceFrequency,
                    ContactDescription = _institutionalInfo.ContactDescription,
                    ContactEmail = _institutionalInfo.ContactEmail,
                    ContactName = _institutionalInfo.ContactName,
                    ContactTelephone = _institutionalInfo.ContactTelephone,
                    ContactTitle = _institutionalInfo.ContactTitle,
                    Notes = _institutionalInfo.Notes,
                    AlternateNames = new List<string> {
_names[0].AlternateName, _names[1].AlternateName } //Here problem
occurs
                };




2015-09-22 16:23 GMT+02:00 Wiktor <interneo@gmail.com>:
