### ISSUE TITLE
SA0102: CSharp.CsParser: A syntax error has been discoved in...

### ISSUE THREAD

**Issue by teatime** [Visual-Stylecop/Visual-StyleCop#22]
The first line of the following statement seems to cause the above error:
```C#
string sql = @"
                SELECT *
                FROM SomeTable";
```
It appears the [verbatim string literal](https://msdn.microsoft.com/en-us/library/aa691090(v=vs.71).aspx) is not been recognised.

**Comment by ptittof57** [comment]
Same as #20

**Comment by ptittof57** [comment]
Fixed in version 4.7.57.0

**Comment by teatime** [comment]
Ok sorry for duplicate. Although I am running v4.7.56.4 and it is occurring for me.

**Comment by ptittof57** [comment]
No problem ;) it should be ok with new version else I reopen #20 if someone find another case.

**Comment by teatime** [comment]
Ah now I see, VS is not auto updating it, thought I had the latest one. Doh!

**Comment by teatime** [comment]
Cool, just updated and re-ran, seems to work perfectly now.
Anyway cheers for the whole thing :-)
