### ISSUE TITLE
Null propagation operator with new line causing exception

### ISSUE THREAD

**Issue by Yavari** [Visual-Stylecop/Visual-StyleCop#26]
I am getting a parser exception with following code in version 4.7.57.0:
            
           var list = new List<string>();
            var length = list.FirstOrDefault()?
                             .Length;

**Comment by sharwell** [comment]
We actually approved a new spacing rule to catch this case:

DotNetAnalyzers/StyleCopAnalyzers#827

**Comment by ptittof57** [comment]
@sharwell I am agree with this new spacing rule. I'll fix the parser and then I'll implement this new rule.
Thanks for this information ;)

**Comment by sharwell** [comment]
@ptittof57 We haven't implemented it yet, but I went ahead and assigned a number to it so we can be in sync. :+1:

**Comment by ptittof57** [comment]
Fixed in version 4.7.58.3
