### ISSUE TITLE
SA0102 : CSharp.CsParser : A syntax error has been discovered ... but compiler don't cry

### ISSUE THREAD

**Issue by RalfRandermann** [Visual-Stylecop/Visual-StyleCop#32]
I use nameof in switch statement like this code
...
            switch (typeof(O).Name)
            {
                case nameof(CompanyFolderModel):
                    result = this.GetCompanyFolderModel(name) as O;
                    break;
...
compiler accept this. StyleCop fails with syntax error.

Regards
Ralf

**Comment by ptittof57** [comment]
Fixed in the next release
