### ISSUE TITLE
nameof() doesn't seem to be supported

### ISSUE THREAD

**Issue by adescre** [Visual-Stylecop/Visual-StyleCop#34]
I'm getting this error on a line that contains nameof()
> 1>D:\Dev\Project\Search.cs(89,1): error : SA0102 : CSharp.CsParser : A syntax error has been discovered in file D:\Dev\Project\Search.cs on line 89.

My line 89 looks like this:
```CSharp
nameof(this.index.SearchAsync),
```

**Comment by adescre** [comment]
Nevermind, it looks like it's fixed in the next release.
https://github.com/Visual-Stylecop/Visual-StyleCop/issues/32

**Comment by adescre** [comment]
Actually, it looks like it's only partially fixed. The specific case I gave still beaks. If I change the code something like this:
```CSharp
nameof(Index.SearchAsync),
```
It works fine.

**Comment by ptittof57** [comment]
Fixed in the next release
