### ISSUE TITLE
NullCoalescingSymbol parsing error

### ISSUE THREAD

**Issue by CFlatWouldbeMinor** [Visual-Stylecop/Visual-StyleCop#36]
Hi Christoph,

I think there is a not considered use case with the NullCoalescingSymbol Symbol.
Line 8 of the The following code results in an error in VisualStyleCop in parsing the file
    internal class myclass
    {
        private bool? singleBitValue;

        private bool? foo(object obj)
        {
            this.singleBitValue = obj as bool?;
            this.singleBitValue = obj as bool? ?? false;
            return true ? true : false;
        }
    }

I was able to fix it by adding a check for checkNullCondition
In StyleCop.CSharp.CodeLexer.GetOperatorSymbor on line 2056

if (character == '?' **&& checkNullCondition.Length == 0**)

In my opinion this makes sense as there must not be any tokes between the ?? operator.
Do you think it is possible to update the code accordingly?
Kind Regards
Ruedi

**Comment by ptittof57** [comment]
Fixed in the next release, thanks a lot for your help ;)
