### ISSUE TITLE
SA0102 issue when using expression body for properties (C# 6)

### ISSUE THREAD

**Issue by AdnanDervisevic** [Visual-Stylecop/Visual-StyleCop#40]
We recently switched to C# 6 with VS2015 at work and after using ReSharper's kind suggestions to start going to C# 6 features like properties to expression body, I got an SA0102 issue with both the lines below. 

public IEnumerable<double> SelectableShiftHours => CreateSelectableShiftHours();

public OptimisationDayOfWeekEnum SelectedDay => selectedDay; (just a standard backing field to see if it was the method that did it)

Build 4.7.58.3

**Comment by ptittof57** [comment]
Hi @AdnanDervisevic, Could you post your complete code please because it seems to work on my side. Please not that Visual-StyleCop is not compatible with R#

**Comment by AdnanDervisevic** [comment]
That is weird, https://gist.github.com/AdnanDervisevic/1e037c6996940e1c9d3b is a gist containing some of my code with some corporate identifiers removed but it doesn't matter where or how I do it, I still shows up as an internal error... No matter what type it returns or how I construct it, I get an internal error :(

**Comment by ptittof57** [comment]
I tried to run Visual-StyleCop V4.7.58.3 with your file and it works as expected. Please try to uninstall the extension from visual studio and remove all occurences of StyleCop.dll to avoid conflicts and then reinstall Visual-StyleCop extension.
