### ISSUE TITLE
SA0102 With string interpolation

### ISSUE THREAD

**Issue by ptittof57** [Visual-Stylecop/Visual-StyleCop#42]
Since I have a problem with string interpolation, I'll post it right here and won't open a new issue.
My code is

```csharp
var message = $"ConnectionString missing: {ConfigurationManager.AppSettings["ConnectionStringName"]}";
```
The code analyzer gives a warning SA0102.

I guess it's a problem with the quotation marks inside of the curly brackets

#37

**Comment by ptittof57** [comment]
Fixed in the next release

**Comment by sachokFoX** [comment]
Found one more case
```
$"\"Names\":[{{\"Name\":\"Foo\"}}]"
```

but this works fine
```
$@"""Names"":[{{""Name"":""Foo""}}]"
```

problem with escaping
```
\"
```
inside string interpolation

**Comment by steelerc** [comment]
Still another example of throwing SA0102 but the code works.
return $"{myNumber}_{anotherNumberString}_{quantity.GetValueOrDefault()}_{creationDate.ToString("yyyyMMdd")}";

**Comment by schoetbi** [comment]
Also this one
```
var csBuilder = new NpgsqlConnectionStringBuilder
{
  ConnectionString = connectionString,
  ["POOLING"] = "false"
};
```
