### ISSUE TITLE
Visual-StyleCop.Build does not work

### ISSUE THREAD

**Issue by FFelling** [Visual-Stylecop/Visual-StyleCop#43]
Hi,

I am trying to install the Visual-StyleCop.Build in my solution. But it doesnot work on the build server. The build failed with the message.

error MSB4018: The "StyleCopTask" task failed unexpectedly.
error MSB4018: System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'
error MSB4018:    at StyleCop.StyleCopTask.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() 
error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()

Can somebody give me some more hints, I have search on the internet but I have not yet found the solution.

Grtz.

**Comment by ptittof57** [comment]
Hi @FFelling,

did you try to search previous stylecop.dll on your server and remove them ?
FAQ in progress : https://github.com/Visual-Stylecop/Visual-StyleCop/wiki/Cleaning-Install

**Comment by sachokFoX** [comment]
@FFelling installing .NET 4.6 on target machine fix problem. I had the same issue.

**Comment by FFelling** [comment]
@ptittof57, @sachokFoX we will try your suggestions next week.
Thanks for the response.
