### ISSUE TITLE
Invalid Syntax reported for valid C#

### ISSUE THREAD

**Issue by vgriph** [Visual-Stylecop/Visual-StyleCop#44]
The following valid C# snippet is reported as a syntax error.

workArea.Leave(x => HandleWorkAreaLogoutLeave(wa, x, obj as bool? ?? true));

Name:	SyntaxException
Namespace:	StyleCop.CSharp.CsParser
Description:

**Comment by y-kitami** [comment]
It seems error has occurred with some new syntax on C# 6.0.

On my env, the same error appears on part of method with lambda expression.
But on my env, it was repaired by reinstall.

see: https://github.com/Visual-Stylecop/Visual-StyleCop/wiki/Cleaning-Install
