### ISSUE TITLE
C#6 features still not supported

### ISSUE THREAD

**Issue by matteo-mosca** [Visual-Stylecop/Visual-StyleCop#46]
Hi, I've already checked issue #7 where it says this has been resolved, however I just intalled Visual-Stylecop.MSBuild from nuget, version 4.7.58.3 and I am getting the SA0102 error on all the C#6 features that I tried out, like:

```c#
try
{

}
catch (Exception) when (true)
{

}
```

or

```c#
public virtual ICollection<CostType> CostTypes { get; protected set; } = new List<CostType>();
```

Am I doing anything wrong or there is a regression?

Thanks.

**Comment by matteo-mosca** [comment]
Also, another different error related to C#6 features is this. When using null-conditional operators like this:

var a = company?.Id;

I am getting the SA1101 error, telling me to use the "this" keyword before "Id" as "Id" is a class member (I also have an Id property in my class where I am writing this line of code)

Thanks.

**Comment by cristianmad** [comment]
I am running into the same problems reported above plus a few other variations related to the null conditional operator.
For now, this is forcing us to stop treating StyleCop warnings as errors in order to not declare the builds as being broken on the build system.

Could you please have a look at it?

Thanks,

PS: We love StyleCop and appreciate the time you guys put into maintaining it.

**Comment by kopelli** [comment]
So I forked the repo to try and fix error about the Null Propagation reporting SA1101. Found an interesting tidbit: It only reports this issue if the member exists in the current class. So in the example that @matteo-mosca provided, the class that code is in must also have an `Id` field/property.

**Comment by cristianmad** [comment]
Sounds great,
 Any ETA for a release (nuget)? I would test it and let you know how it goes.

**Comment by ptittof57** [comment]
Only second bug is fixed so I reopen

**Comment by ptittof57** [comment]
Everything works fine for first post issue.
