### ISSUE TITLE
Installing in VS2015 as user fails

### ISSUE THREAD

**Issue by Dawnkeeper** [Visual-Stylecop/Visual-StyleCop#52]
Trying to install the extension in a VS2015 that is not run by an administrator causes the installer to use up all available memory and crash.

**Comment by Dawnkeeper** [comment]
Additionally running as a user after installing with admin rights also fails due to a constructor not being found. 
![image](https://cloud.githubusercontent.com/assets/9679382/12549037/d0822096-c35a-11e5-920b-40e06eba9c56.png)

**Comment by ptittof57** [comment]
Please check : https://github.com/Visual-Stylecop/Visual-StyleCop/wiki/Cleaning-Install
and #16

**Comment by Dawnkeeper** [comment]
Thanks fro the reply.

Unfortunately StlyeCop is woven into the build process and has to work on the build server as well.

Seems like I'll have to drop using the extension for now =/

**Comment by ptittof57** [comment]
Some VS Extensions use previous version of StyleCop (4.7.49) as reference.
Then the conflict occurs, I can't do anything for now.
