### ISSUE TITLE
SA0102 With string interpolation on escaped double quote

### ISSUE THREAD

**Issue by MaceWindu** [Visual-Stylecop/Visual-StyleCop#56]
See this comment
https://github.com/Visual-Stylecop/Visual-StyleCop/issues/42#issuecomment-163362852
Could confirm that it fails on latest release (4.7.59)

**Comment by v1r7u** [comment]
It's failing on 4.7.59.
For instance, string $"Blah-blah-blah \"{value}\"" produces SA0102 CsParser exception.

**Comment by steelerc** [comment]
Failing on 4.7.59 as well:
return $"{this.Policy.PolicyNumber}_{normalizedFormNumber}_{quantityOrder.GetValueOrDefault()}_{documentCreationDate.ToString("yyyyMMdd")}";

The failing piece is the documentCreationDate.ToString("yyyyMMdd")

**Comment by sergey-netdev** [comment]
Also fails on this:
`$"hello \"world\""`

**Comment by sonergonul** [comment]
This is _still_ an issue on the last version, right?

For example;

`$"MyVersion_{SessionHandler.Customer}_{DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")}.tif"`

fails..
