### ISSUE TITLE
SA1125 : Use the shorthand of the nullable type inside of nameof operator

### ISSUE THREAD

**Issue by MaceWindu** [Visual-Stylecop/Visual-StyleCop#57]
```
nameof(Nullable<int>.Value)
```

StyleCop complains:

```
Error       SA1125 : CSharp.Readability : Use the shorthand of the nullable type
```

Problem here is that nameof operator doesn't accept shorthand notation for nullables

**Comment by ptittof57** [comment]
Allowed in the next release

**Comment by MaceWindu** [comment]
Thanks.
For anyone interested in this, here is somewhat related issue in Roslyn repository:
https://github.com/dotnet/roslyn/issues/4827
