### ISSUE TITLE
Proposal: remove new rule SA1127 (AvoidStringFormatUseStringInterpolation)

### ISSUE THREAD

**Issue by sharwell** [Visual-Stylecop/Visual-StyleCop#6]
I propose rule SA1127 be removed for the following reasons:

1. String interpolation does not always offer readability benefits over `string.Format`. Calls to `string.Format` have the ability to use the standard call syntax with one argument per line to express long formatting operations. These uses should not be required to suppress a warning.

2. The use of string interpolation increases the complexity of updating single-culture code to properly support localization. The rule is therefore prone to increasing the technical debt associated with young projects that have not yet moved to proper resource-based strings.

Conclusion: the benefits provided by string interpolation are not consistent across a code base, and therefore do not meet the bar for declaring a general readability rule that will apply to whole code bases. Support for string interpolation should be limited to the creation of refactoring operations which can be applied to specific calls to `string.Format` if and when developers see readability benefits.

**Comment by sharwell** [comment]
Note that this rule also conflicts with [SA1127: Generic type constraints must be on their own line](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1127.md) in StyleCop Analyzers.

**Comment by ptittof57** [comment]
Rule removed in the next release.
