### ISSUE TITLE
Can't open settings dialog.

### ISSUE THREAD

**Issue by terasato** [Visual-Stylecop/Visual-StyleCop#61]
In Solution Explorer -> Right click Project -> click "StyleCop Settings" causes crash.
I'm using VS2015 Community in English, and the latest add-in is installed via "Extensions and Updates".

Dialog
![2016-02-16](https://cloud.githubusercontent.com/assets/2510414/13070209/2e62c664-d4ce-11e5-821a-1ed0e6293c4a.png)

Info about my VS.
![2016-02-16 1](https://cloud.githubusercontent.com/assets/2510414/13070210/30681112-d4ce-11e5-89c2-3bb2f72da592.png)

**Comment by ptittof57** [comment]
@terasato do you have some VS products from yWorks ? It seems that Visual StyleCop is trying to load a dll from yWorks. Everything works on my side for VS2015 Community in French.

**Comment by terasato** [comment]
@ptittof57 thank you for your reply.
I examined the issue and found that the source is ["Visual StyleCop"](https://visualstudiogallery.msdn.microsoft.com/cac2a05b-6eb6-4fa2-95b9-1f8d011e6cae?SRC=VSIDE), an VS extension.
I'm sorry for bothering you, and a lot of thank you. Bye,
